### ISSUE TITLE
Using custom separators in CSV files

### ISSUE THREAD

**Issue by SjakoAnimatix** [kolibril13/blender_csv_import#19]
Hi, thx for this very needed extension.

I tried to import several simple .csv's but it gives me only verts/points in the origin. No attributes visible in the spreadsheet viewer.
Tried to download the example datafile but that is not available (404). I can't figure out what goes wrong.

**Comment by kolibril13** [comment]
Hi there!
you find the sample dataset here:
https://github.com/kolibril13/blender_csv_import/blob/main/docs/sample_datasets/data_california_housing_normalized.csv
I've also fixed the link.
You have to select the object to see the attributes in the spreadsheet. 
you'll also find a video tutorial at https://extensions.blender.org/add-ons/csv-importer/

**Comment by SjakoAnimatix** [comment]
Hi

Thx for reponding. With the help of your samplefile I discovered that all .csv export (Numbers and Excel) on my system use ; as a delimiter in stead of ,  This seems to be a regional (Dutch) problem. Switching to another region does not solve this problem. Replacing the ; for a , in the .csv file does.

Thx again, kind regards,
Sjako

**Comment by kolibril13** [comment]
>  I imagine polars (which does the parsing) can handle different file delimiters.

yep, that's possible, like in the code snippet below.
I think it's not worth the time to build a User Interface for it. 
If someone wants to use custom separators, they can use the below snippet from Python:
```py
from io import StringIO
import polars as pl
from csv_importer.parsers import polars_df_to_bob

csv_data = StringIO(
"""FloatVal;IntVal;BoolVal;StringVal
1.23;10;true;Hello
4.56;20;false;World"""
)
df = pl.read_csv(csv_data, separator=';')
bob = polars_df_to_bob(df, name="Test")
```
